#!/bin/bash
# ============================================================
# Yaksha FAQ Portal — Full Stack Runner (with env setup)
# Usage: ./run.sh
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR"
BACKEND="$ROOT/backend"
FRONTEND="$ROOT/frontend"

FONT="\033[94m"
OK="\033[92m"
WARN="\033[93m"
ERROR="\033[91m"
RESET="\033[0m"

log()  { echo -e "${FONT}[yaksha]${RESET} $1"; }
ok()   { echo -e "${OK}[✔]${RESET} $1"; }
warn() { echo -e "${WARN}[!]${RESET} $1"; }
die()  { echo -e "${ERROR}[✘]${RESET} $1" >&2; exit 1; }

BACKEND_PID=""
FRONTEND_PID=""

cleanup() {
  echo ""
  warn "Shutting down..."
  [ -n "$BACKEND_PID" ] && kill $BACKEND_PID 2>/dev/null || true
  [ -n "$FRONTEND_PID" ] && kill $FRONTEND_PID 2>/dev/null || true
  ok "Done."
  exit 0
}
trap cleanup SIGINT SIGTERM

# ── Ensure .env exists ─────────────────────────────────────────────────────────
ensure_env() {
  local env_file="$BACKEND/.env"
  if [ ! -f "$env_file" ]; then
    if [ -f "$BACKEND/.env.example" ]; then
      log "Creating .env from .env.example..."
      cp "$BACKEND/.env.example" "$env_file"
    else
      touch "$env_file"
    fi
  fi
}

# ── Read a var from .env (returns empty if not set) ───────────────────────────
read_env() {
  local var_name=$1
  grep "^${var_name}=" "$BACKEND/.env" 2>/dev/null | head -1 | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g"
}

# ── Write a var to .env.local ──────────────────────────────────────────────────
write_env_local() {
  local var_name=$1
  local value=$2
  local local_file="$BACKEND/.env.local"
  # Remove existing entry
  grep -v "^${var_name}=" "$local_file" 2>/dev/null > "$local_file.tmp" || true
  mv "$local_file.tmp" "$local_file"
  # Append new entry
  echo "${var_name}=${value}" >> "$local_file"
}

# ── Prompt user for a value if not in .env ───────────────────────────────────
prompt_if_missing() {
  local var_name=$1
  local description=$2
  local current
  current=$(read_env "$var_name")
  [ -n "$current" ] && current=$(grep "^${var_name}=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
  [ -n "$current" ] && return 0

  echo ""
  echo -e "${WARN}Missing: ${var_name}${RESET}"
  echo -e "  $description"
  echo -n "  Enter value: "
  read -r value
  if [ -z "$value" ]; then
    die "${var_name} is required — cannot continue"
  fi
  write_env_local "$var_name" "$value"
  ok "Saved ${var_name}"
}

# ── Optional var prompt ────────────────────────────────────────────────────────
prompt_optional() {
  local var_name=$1
  local description=$2
  local current
  current=$(grep "^${var_name}=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
  [ -n "$current" ] && return 0

  echo ""
  echo -e "  ${description}"
  echo -n "  Enter value (or press Enter to skip): "
  read -r value
  [ -n "$value" ] && write_env_local "$var_name" "$value" && ok "Saved ${var_name}"
}

# ── Setup env vars ─────────────────────────────────────────────────────────────
setup_env() {
  ensure_env

  # Create .env.local if it doesn't exist
  local local_file="$BACKEND/.env.local"
  if [ ! -f "$local_file" ]; then
    {
      echo "# Local env overrides — generated by run.sh"
      echo "# This file is NOT committed to git"
      echo ""
    } > "$local_file"
  fi

  # ── Fast path: skip prompts if ALL required vars are already in .env or .env.local ──
  local required_vars="MONGODB_URI JWT_SECRET"
  local all_set=true
  for var in $required_vars; do
    local val_in_env=$(grep "^${var}=" "$BACKEND/.env" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
    local val_in_local=$(grep "^${var}=" "$BACKEND/.env.local" 2>/dev/null | cut -d'=' -f2- | sed "s/^['\"]//g;s/['\"]$//g")
    if [ -z "$val_in_env" ] && [ -z "$val_in_local" ]; then
      all_set=false
      break
    fi
  done

  if [ "$all_set" = true ]; then
    echo ""
    ok "All required env vars found in .env / .env.local — skipping prompts."
    echo ""
    return 0
  fi

  echo ""
  echo "=============================================="
  echo "  Yaksha FAQ Portal — Env Setup"
  echo "=============================================="

  prompt_if_missing "MONGODB_URI" "MongoDB Atlas connection string"
  prompt_if_missing "JWT_SECRET"    "JWT secret — run: openssl rand -hex 32"

  echo ""
  echo "  --- Optional (press Enter to skip) ---"
  prompt_optional "MINIMAX_API_KEY"     "MINIMAX_API_KEY (for Zoom transcript extraction)"
  prompt_optional "ZOOM_CLIENT_ID"      "ZOOM_CLIENT_ID (from Zoom App marketplace)"
  prompt_optional "ZOOM_CLIENT_SECRET"  "ZOOM_CLIENT_SECRET (from Zoom App marketplace)"
  prompt_optional "REDIS_URL"           "REDIS_URL (Upstash Redis — enables cross-instance cache)"
  prompt_optional "REDIS_TOKEN"         "REDIS_TOKEN (Upstash REST API token)"
  prompt_optional "SENTRY_DSN"          "SENTRY_DSN (Sentry error tracking DSN)"

  echo ""
  ok "Env setup complete — saved to .env.local"
}

# ── Wait for backend ─────────────────────────────────────────────────────────────
wait_for_backend() {
  local max_wait=20
  local waited=0
  log "Waiting for backend to be ready..."
  while [ $waited -lt $max_wait ]; do
    local status=$(curl -sf --max-time 2 http://localhost:6767/api/health 2>/dev/null \
      | python3 -c "import sys,json; print(json.load(sys.stdin).get('db','?'))" 2>/dev/null \
      || echo "waiting")
    if [ "$status" = "connected" ]; then
      ok "MongoDB connected"
      return 0
    fi
    sleep 2
    waited=$((waited + 2))
    echo -n "."
  done
  warn "Backend DB not connected after ${max_wait}s — continuing anyway"
}

# ── Start backend ──────────────────────────────────────────────────────────────
start_backend() {
  log "Starting backend..."
  cd "$BACKEND"
  set -a
  source ".env" 2>/dev/null || true
  source ".env.local" 2>/dev/null || true
  set +a
  npm run dev &
  BACKEND_PID=$!
  ok "Backend PID $BACKEND_PID"
}

# ── Start frontend ──────────────────────────────────────────────────────────────
start_frontend() {
  log "Starting frontend..."
  cd "$FRONTEND"
  npm run dev &
  FRONTEND_PID=$!
  ok "Frontend PID $FRONTEND_PID"
}

# ── Kill existing processes ──────────────────────────────────────────────────────
kill_existing() {
  local killed=0
  for port in 5173 6767; do
    local pid=$(lsof -ti:$port 2>/dev/null || true)
    if [ -n "$pid" ]; then
      warn "Killing existing process on port $port (PID $pid)"
      kill -9 $pid 2>/dev/null || true
      killed=1
    fi
  done
  [ $killed -eq 1 ] && sleep 1 && ok "Cleared."
}

check_url_alive() {
  curl -sf --max-time 2 http://localhost:5173 > /dev/null 2>&1
}

# ── Main ───────────────────────────────────────────────────────────────────────
echo ""
log "Yaksha FAQ Portal"
echo ""

setup_env

if check_url_alive; then
  warn "Frontend already live on 5173 — clearing ports"
  kill_existing
else
  ok "Port 5173 is free"
fi

start_backend
wait_for_backend
start_frontend

echo ""
ok "Backend  →  http://localhost:6767"
ok "Frontend →  http://localhost:5173"
echo ""
log "Press Ctrl+C to stop"
echo ""

wait
