const { createClient } = require('@libsql/client');
require('dotenv').config();

// Turso DB Connection
const db = createClient({
    url: process.env.TURSO_DATABASE_URL,
    authToken: process.env.TURSO_AUTH_TOKEN
});

// Aapke saare official FAQs ka data
const oldFaqs = [
    // --- Section 1: About the internship ---
    { id: "1.1", category: "1. About the internship", question: "1.1 What is the Vicharanashala internship?", answer: "The Vicharanashala internship is a structured, self-paced research internship programme run by the Vicharanashala Lab at IIT Ropar. It focuses on Applied AI and open-source software engineering. Interns work on real-world projects, learn through coursework, and contribute to open-source repositories — all remotely." },
    { id: "1.2", category: "1. About the internship", question: "1.2 What is VINS?", answer: "VINS stands for Vicharanashala INternship (online/Self-paced). It is the online, self-paced track of the internship where you complete coursework, daily standups, and project work remotely at your own pace within the programme timeline." },
    { id: "1.3", category: "1. About the internship", question: "1.3 What are the phases of VINS, and what do the badges mean?", answer: "VINS has multiple phases. Phase 1 involves coursework and learning fundamentals through the Vibe LMS platform. Phase 2 involves team-based project work. Badges represent milestones and achievements — they indicate your progress through the programme and are visible on your dashboard." },
    { id: "1.4", category: "1. About the internship", question: "1.4 Who is the internship for? Are alumni eligible?", answer: "The internship is primarily for current undergraduate and postgraduate students from any college in India. Alumni who have recently graduated (within the last year) may also be eligible depending on the cohort. Check the current cycle's eligibility criteria on the Overview page." },
    { id: "1.5", category: "1. About the internship", question: "1.5 Is this the same as IIT Ropar's official Summer Research Internship?", answer: "No. This is a separate programme run by the Vicharanashala Lab. It is not the same as IIT Ropar's official Summer Research Internship (SURI). However, it is conducted under the guidance of faculty at IIT Ropar and carries its own certificate." },
    { id: "1.6", category: "1. About the internship", question: "1.6 I have to attend my class tomorrow/today/some day — can I take leave?", answer: "Yes. The internship is self-paced and designed to accommodate your academic schedule. You do not need to request leave for attending classes. Just ensure you meet the weekly participation requirements and complete your tasks within the deadlines." },

    // --- Section 2: Timing and dates ---
    { id: "2.1", category: "2. Timing and dates", question: "2.1 When can I start?", answer: "Your start date is mentioned in your offer letter. You will receive access to the platform and onboarding materials on or before your start date. Check your dashboard for the exact timeline." },
    { id: "2.2", category: "2. Timing and dates", question: "2.2 How long is the internship?", answer: "The internship typically runs for 8–12 weeks depending on the cohort and track. The exact duration is specified in your offer letter. Some tracks may have extended timelines for project completion." },
    { id: "2.3", category: "2. Timing and dates", question: "2.3 Can I start in July, August or later if I have exams now?", answer: "Start dates are fixed per cohort. If you have exams, you can request a later start date during the application process. However, once assigned to a cohort, the start date cannot be changed significantly. Check section 4.8 for date change policies." },
    { id: "2.4", category: "2. Timing and dates", question: "2.4 Can I start with the cohort and take a relaxation during my exam window?", answer: "Yes, you can start with your cohort and take a brief relaxation period during exams. However, you must inform the team in advance and ensure your participation requirements are met on a rolling basis. Extended breaks may affect your Spurti Points." },
    { id: "2.5", category: "2. Timing and dates", question: "2.5 Can I take leave or get an exemption during the internship for an exam scheduled in June?", answer: "The internship is self-paced, so you can manage your time around exams. There is no formal 'leave' system. Just ensure you maintain minimum participation levels. If you have a major exam period, inform your mentor and adjust your workload accordingly." },
    { id: "2.6", category: "2. Timing and dates", question: "2.6 Are orientation session recordings shared with interns, and can project or group assignments be changed after watching them?", answer: "Yes, orientation session recordings are shared on the platform. However, project and group assignments are typically not changed after the orientation. If you have a genuine concern, reach out to the programme team through the dashboard chat." },

    // --- Section 3: NOC (No Objection Certificate) ---
    { id: "3.1", category: "3. NOC (No Objection Certificate)", question: "3.1 What dates do I put on the NOC?", answer: "Use the start and end dates mentioned in your offer letter. These are the official internship dates that should appear on your NOC." },
    { id: "3.2", category: "3. NOC (No Objection Certificate)", question: "3.2 Who can sign the NOC?", answer: "The NOC should be signed by your Head of Department (HOD), Dean, or Program Chair — essentially any authorized faculty member who can officially confirm that your college has no objection to you undertaking this internship." },
    { id: "3.3", category: "3. NOC (No Objection Certificate)", question: "3.3 When do I submit the NOC? Is the deadline hard?", answer: "The NOC submission deadline is mentioned in your offer letter and dashboard. Yes, the deadline is firm. Late submissions may delay your internship start or result in offer cancellation. Submit as early as possible." },
    { id: "3.4", category: "3. NOC (No Objection Certificate)", question: "3.4 What format should I use? Do I need to design it myself?", answer: "A standard NOC format is provided on your dashboard. You can use that template or your college's own format — both are acceptable. The key requirement is that it must be on official letterhead (if available) and signed by an authorized person." },
    { id: "3.5", category: "3. NOC (No Objection Certificate)", question: "3.5 What if my college / Program Chair gives me an NOC in their own format?", answer: "That's perfectly fine. We accept NOCs in any format as long as it clearly states: (1) your name, (2) the internship organization (Vicharanashala Lab, IIT Ropar), (3) the dates, and (4) has an authorized signature." },
    { id: "3.6", category: "3. NOC (No Objection Certificate)", question: "3.6 Does it need to be signed by hand?", answer: "A physical (wet) signature is preferred, but a digital signature from an authorized person is also accepted. The NOC should not have a typed name in place of a signature — it must be an actual signature (physical or digital)." },
    { id: "3.7", category: "3. NOC (No Objection Certificate)", question: "3.7 Can my HOD email the NOC instead of uploading it?", answer: "No. You must upload the NOC through your dashboard. If your HOD provides it via email, download it and upload it yourself. The system requires a file upload for verification purposes." },
    { id: "3.8", category: "3. NOC (No Objection Certificate)", question: "3.8 How do I download and upload the NOC?", answer: "Log in to your dashboard at samagama.in. Navigate to the NOC section, download the template if needed, get it signed, scan or photograph it clearly, and upload the file (PDF or image format) through the upload button on your dashboard." },
    { id: "3.9", category: "3. NOC (No Objection Certificate)", question: "3.9 What if my NOC is not formally verified?", answer: "If your NOC cannot be formally verified (e.g., missing letterhead, unclear signature), you may be asked to resubmit. Ensure the document is clear, legible, and contains all required information before uploading." },
    { id: "3.10", category: "3. NOC (No Objection Certificate)", question: "3.10 My online course (Masai, NPTEL, Coursera, etc.) won't issue an NOC. What do I do?", answer: "If you are enrolled in an online course/bootcamp that doesn't issue NOCs, contact the programme team through your dashboard chat explaining your situation. They will guide you on alternative documentation that may be accepted." },
    { id: "3.11", category: "3. NOC (No Objection Certificate)", question: "3.11 My HOD/college official wants written confirmation before signing my NOC. What do I show them?", answer: "Show them your offer letter from the programme. It contains all relevant details including the organization name, duration, and nature of the internship. If they need additional confirmation, ask the programme team to provide an official email/letter addressed to your HOD." },
    { id: "3.12", category: "3. NOC (No Objection Certificate)", question: "3.12 Can Prof. Sudarshan Iyengar or a faculty member from IIT Ropar sign my NOC for the internship?", answer: "No. The NOC must be signed by YOUR college's authority (HOD, Dean, or Program Chair). It is a document from your institution confirming they have no objection. IIT Ropar faculty cannot sign your college's NOC." },

    // --- Section 4: Selection, offer letter, and certificate ---
    { id: "4.1", category: "4. Selection, offer letter, and certificate", question: "4.1 How do I know I am selected?", answer: "You will receive a selection notification via email and on your Samagama dashboard. The dashboard status will change to 'Selected' and you'll be able to view next steps including offer letter acceptance and NOC submission." },
    { id: "4.2", category: "4. Selection, offer letter, and certificate", question: "4.2 How do I opt into VINS?", answer: "After selection, you'll see an option on your dashboard to choose between VINS (online/self-paced) and VISE (offline). Select VINS and confirm your preference. This choice may be final depending on the cohort." },
    { id: "4.3", category: "4. Selection, offer letter, and certificate", question: "4.3 When do I get the offer letter?", answer: "The offer letter is generated after you complete the initial steps (profile verification, track selection). It is typically available on your dashboard within a few days of selection confirmation." },
    { id: "4.4", category: "4. Selection, offer letter, and certificate", question: "4.4 Will I get a certificate?", answer: "Yes, you will receive a completion certificate if you successfully complete the internship requirements including coursework, participation, and project deliverables. The certificate is issued by IIT Ropar / Vicharanashala Lab." },
    { id: "4.5", category: "4. Selection, offer letter, and certificate", question: "4.5 How do I confirm my internship dates?", answer: "Your internship dates are confirmed when you accept the offer letter on your dashboard. The dates mentioned in the offer letter become your official internship period." },
    { id: "4.6", category: "4. Selection, offer letter, and certificate", question: "4.6 I am a minor/major in AI student, can I join the programme? I don't need a NOC as I am from IIT Ropar", answer: "If you are a student at IIT Ropar, you may not need an external NOC, but you should still confirm with the programme team. Your eligibility depends on the current cohort's criteria. Check with the team via the dashboard chat." },
    { id: "4.7", category: "4. Selection, offer letter, and certificate", question: "4.7 How do I accept the offer letter?", answer: "Log in to your dashboard, navigate to the offer letter section, review the terms and conditions, and click 'Accept.' You may need to digitally sign or acknowledge the terms before the acceptance is confirmed." },
    { id: "4.8", category: "4. Selection, offer letter, and certificate", question: "4.8 Can I change my internship dates?", answer: "Date changes are generally not allowed after offer acceptance. In exceptional circumstances (medical emergencies, unavoidable academic conflicts), contact the programme team immediately through the dashboard. Changes are granted on a case-by-case basis." },
    { id: "4.9", category: "4. Selection, offer letter, and certificate", question: "4.9 My NOC is not ready but my start date is approaching. What do I do?", answer: "Inform the programme team immediately via the dashboard chat. In some cases, a grace period may be provided. However, your internship activities may be restricted until the NOC is submitted. Start the process with your college as early as possible." },
    { id: "4.10", category: "4. Selection, offer letter, and certificate", question: "4.10 When does my internship actually begin? Will I receive a notification on the day?", answer: "Your internship begins on the start date mentioned in your offer letter. You will receive a notification and access to the orientation materials on or before day 1. Check your email and dashboard on your start date." },
    { id: "4.11", category: "4. Selection, offer letter, and certificate", question: "4.11 Can I switch from VINS (online) to VISE (offline) after being selected?", answer: "Switching between tracks after selection is generally not permitted as it affects resource allocation and planning. If you have a compelling reason, contact the programme team, but approval is not guaranteed." },
    { id: "4.12", category: "4. Selection, offer letter, and certificate", question: "4.12 Can I change my internship dates after the offer letter?", answer: "See question 4.8. Date changes after offer acceptance are handled on a case-by-case basis and only for genuine emergencies. The programme team's decision is final." },

    // --- Section 5: Work, mentorship, and projects ---
    { id: "5.1", category: "5. Work, mentorship, and projects", question: "5.1 What will I work on?", answer: "You will work on real-world projects in Applied AI and open-source software engineering. Projects are assigned based on your skills, interests, and the current research needs. Examples include ML model development, data pipelines, web applications, and research tools." },
    { id: "5.2", category: "5. Work, mentorship, and projects", question: "5.2 How many hours per day?", answer: "The internship is self-paced, but we recommend dedicating 4–6 hours per day. The key metric is output quality and meeting deadlines rather than hours logged. Consistency matters more than long sporadic sessions." },
    { id: "5.3", category: "5. Work, mentorship, and projects", question: "5.3 Who is my mentor?", answer: "Your mentor is assigned after team formation and will be communicated via the dashboard and email. Mentors are typically senior students, researchers, or industry professionals associated with the Vicharanashala Lab." },
    { id: "5.4", category: "5. Work, mentorship, and projects", question: "5.4 Is there a stipend?", answer: "The internship is primarily a learning experience. Stipend availability varies by cohort and track. Check the current cycle's details on the Overview page or your offer letter for specific information about compensation." },
    { id: "5.5", category: "5. Work, mentorship, and projects", question: "5.5 Do I need my own laptop? Should I preload any software?", answer: "Yes, you need your own laptop/computer with a stable internet connection. Recommended software includes: a code editor (VS Code), Git, Python 3.x, and a modern web browser. Specific project requirements will be shared during onboarding." },
    { id: "5.6", category: "5. Work, mentorship, and projects", question: "5.6 I am using a different email on GitHub / Zoom / the learning platform. Is that okay?", answer: "It's best to use the same email across all platforms for consistency. If you must use different emails, make sure your Samagama email is your primary one and inform the team about your alternate emails so they can link your accounts." },
    { id: "5.7", category: "5. Work, mentorship, and projects", question: "5.7 Why has my mentor not been assigned yet, or contacted me on day 1?", answer: "Mentor assignment happens after team formation, which may take a few days after your start date. If you haven't heard from your mentor within the first week, reach out via the dashboard chat. In the meantime, focus on the Phase 1 coursework." },

    // --- Section 6: Code of conduct — communication channels ---
    { id: "6.1", category: "6. Code of conduct — communication channels", question: "6.1 What are the official communication channels?", answer: "The official communication channels are: (1) Samagama dashboard chat (primary), (2) official email from the programme team, (3) Zoom for live sessions, and (4) GitHub for code-related discussions. Do not rely on unofficial WhatsApp groups or personal messages for programme-related queries." },

    // --- Section 7: Interviews Related ---
    { id: "7.1", category: "7. Interviews Related", question: "7.1 My interview is not marked as complete on the dashboard — what do I do?", answer: "Interview status updates may take 24–48 hours to reflect on your dashboard. If it's been longer than that, contact the programme team through the dashboard chat with your interview date and time for them to verify and update your status." },

    // --- Section 8: Certificate ---
    { id: "8.1", category: "8. Certificate", question: "8.1 Does Vicharanashala send a grade report or evaluation to my university for internship credit?", answer: "We provide a completion certificate and can issue a performance letter if requested. However, we do not automatically send grade reports to universities. If your university requires specific documentation, contact the programme team and we'll try to accommodate the request." },
    { id: "8.2", category: "8. Certificate", question: "8.2 Does the Vicharanashala internship certificate specify whether it was completed online or offline?", answer: "The certificate mentions the track (VINS/VISE) which indicates the mode. VINS is the online track and VISE is the offline track. The specific wording may vary by cohort." },
    { id: "8.3", category: "8. Certificate", question: "8.3 Will the completion certificate be a physical hardcopy or an e-certificate?", answer: "The certificate is issued as a digital/e-certificate that can be downloaded from your dashboard. Physical hardcopies are generally not provided, but the digital certificate is verifiable and suitable for all professional purposes." },
    { id: "8.4", category: "8. Certificate", question: "8.4 Is there a WhatsApp group for candidates during the internship?", answer: "Official communication happens through the Samagama platform and Zoom. While informal WhatsApp groups may exist among interns, they are not official channels. Always rely on the dashboard and official emails for important announcements." },

    // --- Section 9: Rosetta — your internship journal ---
    { id: "9.1", category: "9. Rosetta — your internship journal", question: "9.1 What is Rosetta?", answer: "Rosetta is your daily internship journal — a structured reflection tool where you document your learning, challenges, and progress each day. It's a core part of the internship experience designed to build a 'thinking routine.'" },
    { id: "9.2", category: "9. Rosetta — your internship journal", question: "9.2 Why does this exist? Is it just busywork?", answer: "No, it's not busywork. Rosetta is designed to help you develop metacognitive skills — the ability to think about your own thinking. Research shows that daily reflection significantly improves learning outcomes, problem-solving ability, and professional growth." },
    { id: "9.3", category: "9. Rosetta — your internship journal", question: "9.3 What is a 'thinking routine'?", answer: "A thinking routine is a structured pattern of reflection that becomes habitual over time. In Rosetta, this means regularly asking yourself: What did I learn? What challenged me? What will I do differently? This builds self-awareness and continuous improvement habits." },
    { id: "9.4", category: "9. Rosetta — your internship journal", question: "9.4 How do I get my Rosetta journal?", answer: "Your Rosetta journal is accessible from your Samagama dashboard. It will be activated on your internship start date. You'll see daily prompts that guide your reflection entries." },
    { id: "9.5", category: "9. Rosetta — your internship journal", question: "9.5 How do I use it day to day?", answer: "Each day, open your Rosetta journal, read the prompt, and write a thoughtful reflection. It's best done at the end of your work session when your experiences are fresh. Aim to write consistently rather than in bulk." },
    { id: "9.6", category: "9. Rosetta — your internship journal", question: "9.6 How long should each entry be?", answer: "There's no strict word count, but aim for meaningful reflection — typically 150–300 words per entry. Quality matters more than quantity. A thoughtful 150-word entry is better than a superficial 500-word one." },
    { id: "9.7", category: "9. Rosetta — your internship journal", question: "9.7 What is the one rule?", answer: "The one rule is: Write it yourself, in your own words, based on your own genuine experience and reflection. Authenticity is the foundation of Rosetta." },
    { id: "9.8", category: "9. Rosetta — your internship journal", question: "9.8 Can I use ChatGPT or any AI tool to write my entries?", answer: "No. Using AI tools to write your Rosetta entries defeats the entire purpose of the journal. The value comes from YOUR reflection, not generated text. AI-written entries are detectable and will be flagged, potentially affecting your standing in the programme." },
    { id: "9.9", category: "9. Rosetta — your internship journal", question: "9.9 What if I miss a day?", answer: "Missing an occasional day is understandable. Try to make up for it the next day by briefly reflecting on both days. However, consistently missing entries will affect your participation score. Set a daily reminder to build the habit." },
    { id: "9.10", category: "9. Rosetta — your internship journal", question: "9.10 Will anyone read my journal during the internship?", answer: "Yes, your journal entries may be reviewed by the programme team and your mentor. This is to ensure genuine participation and to provide feedback. Your entries are kept confidential within the programme team." },
    { id: "9.11", category: "9. Rosetta — your internship journal", question: "9.11 Can the prompts change mid-internship?", answer: "Yes, prompts may evolve as the internship progresses to match the phase you're in. Early prompts focus on learning and adaptation, while later ones may focus on project progress and deeper technical reflection." },
    { id: "9.12", category: "9. Rosetta — your internship journal", question: "9.12 How do I submit Rosetta at the end?", answer: "Rosetta entries are automatically saved as you write them. At the end of the internship, your complete journal is compiled automatically. There's no separate submission step — just ensure all your daily entries are completed." },
    { id: "9.13", category: "9. Rosetta — your internship journal", question: "9.13 I have a question about Rosetta that is not answered here. What do I do?", answer: "Ask your question through the Samagama dashboard chat. The programme team monitors it regularly and will respond to your query." },
    { id: "9.14", category: "9. Rosetta — your internship journal", question: "9.14 My college requires a written confirmation that the internship is self-paced and will not clash with college classes — what document can I share with them?", answer: "You can share your offer letter which mentions the self-paced nature of the programme. If your college needs a specific letter, contact the programme team through the dashboard and request a confirmation letter addressed to your institution." },

    // --- Section 10: Phase 1 — coursework, Vibe LMS, and live sessions ---
    { id: "10.1", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.1 I've already completed a course (Vinternship, Pinternship, MERN, or AI) with you in an earlier cohort — am I exempt from repeating it?", answer: "This depends on the specific course and how recently you completed it. Contact the programme team with details of your previous completion (cohort, course name, completion date) and they will advise on exemptions." },
    { id: "10.2", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.2 How do I register for the AI Fundamentals course on Vibe?", answer: "Registration instructions are provided on your dashboard after your internship begins. You'll receive an invite link to the Vibe platform. Use your Samagama email to register and access the course materials." },
    { id: "10.3", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.3 I registered on Vibe with a different email than my Samagama email — is that OK?", answer: "It's strongly recommended to use the same email. If you've already registered with a different email, inform the programme team so they can link your accounts. Using different emails may cause issues with progress tracking." },
    { id: "10.4", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.4 Are live sessions mandatory if I'm on the viva route?", answer: "Live session requirements depend on your specific track and route. Check your dashboard for the attendance requirements applicable to your route. Generally, key sessions like kickoff and standups have attendance expectations." },
    { id: "10.5", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.5 When and how do I get the Zoom link for the kickoff meeting?", answer: "The Zoom link for the kickoff meeting is shared via email and posted on your dashboard 24–48 hours before the session. Check both your email (including spam) and dashboard on the day before the kickoff." },
    { id: "10.6", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.6 How do I get the link for the daily Zoom standups? Are they mandatory?", answer: "Daily standup links are posted on your dashboard. Whether they are mandatory depends on your track — check the participation requirements on your dashboard. Regular attendance is strongly encouraged as it contributes to your Spurti Points." },
    { id: "10.7", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.7 How do I provide my Zoom ID, and why does it matter?", answer: "Your Zoom ID is used for attendance tracking during live sessions. Provide it through your dashboard profile settings. Using a consistent Zoom ID ensures your attendance is properly recorded and linked to your account." },
    { id: "10.8", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.8 I saved the wrong Zoom ID — can I change it?", answer: "Yes, you can update your Zoom ID from your dashboard profile settings. Make the change before your next live session to ensure proper attendance tracking." },
    { id: "10.9", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.9 Can we register and start the vibe courses before our internship date formally starts?", answer: "Access to Vibe courses is typically granted on or after your official start date. Early access may be available in some cases — check your dashboard for any pre-start materials or contact the programme team." },
    { id: "10.10", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.10 What are the attendance and participation rules?", answer: "Attendance and participation are tracked through multiple metrics: live session attendance, coursework progress, Rosetta journal entries, and standup participation. Specific requirements are detailed on your dashboard under the 'Participation' section." },
    { id: "10.11", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.11 What are Spurti Points (SP)? Do they affect my internship?", answer: "Spurti Points are a participation metric that tracks your engagement across all internship activities. They reflect your consistency and involvement. While SP alone don't determine outcomes, consistently low SP may trigger a review of your standing. See section 11 for details." },
    { id: "10.12", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.12 What are the live-session (Zoom) participation and conduct rules?", answer: "During live sessions: keep your camera on (if required), stay muted unless speaking, use the chat for questions, be punctual, and maintain professional conduct. Disruptive behavior may result in removal from the session and SP deduction." },
    { id: "10.13", category: "10. Phase 1 — coursework, Vibe LMS, and live sessions", question: "10.13 I got 'Failed to submit poll. Error: 100035000' during a session — what does it mean, and will I lose poll credit?", answer: "This is a Zoom technical error and not your fault. Your attendance is still recorded through other means. If you're concerned about poll credit, report the error via the dashboard chat with a screenshot and the session date/time." },

    // --- Section 11: Spurti Points ---
    { id: "11.1", category: "11. Spurti Points", question: "11.1 What are Spurti Points?", answer: "Spurti Points (SP) are a composite metric that measures your overall participation and engagement in the internship. They are calculated based on multiple factors including attendance, coursework progress, journal entries, and active participation." },
    { id: "11.2", category: "11. Spurti Points", question: "11.2 Is SP a finished system?", answer: "SP is continuously evolving. The calculation methodology may be refined across cohorts based on feedback and programme needs. The current version reflects the best balance of participation metrics we've identified." },
    { id: "11.3", category: "11. Spurti Points", question: "11.3 How much importance should I give to my SP number?", answer: "SP is an indicator, not the sole determinant of your internship outcome. Focus on genuine learning and consistent participation rather than gaming the number. If your SP is healthy, it means you're on track. If it's low, it's a signal to increase your engagement." },
    { id: "11.4", category: "11. Spurti Points", question: "11.4 Can I be terminated or excused because of low SP?", answer: "Consistently low SP may trigger a warning and review. If participation remains critically low despite warnings, the programme team may decide to excuse you from the internship. This is a last resort — the team will always reach out before taking such action." },
    { id: "11.5", category: "11. Spurti Points", question: "11.5 What if my SP shows as zero or even negative?", answer: "A zero or negative SP indicates very low or no participation. This is a serious signal. Check your dashboard for missed activities and immediately resume regular participation. Contact the programme team if you believe there's an error in calculation." },
    { id: "11.6", category: "11. Spurti Points", question: "11.6 Does a higher SP bring any benefits?", answer: "High SP reflects strong engagement and may be considered positively for recommendations, project assignments, and recognition. However, the primary benefit is the learning and growth that comes from consistent participation." },
    { id: "11.7", category: "11. Spurti Points", question: "11.7 If SP does not determine outcomes, what does?", answer: "Outcomes are determined by a holistic evaluation: project quality, learning demonstrated, teamwork, consistency, mentor feedback, and overall contribution. SP is one input among many — think of it as a health indicator rather than a final grade." },
    { id: "11.8", category: "11. Spurti Points", question: "11.8 What are the participation requirements tracked strictly?", answer: "Strictly tracked requirements include: daily Rosetta entries, coursework deadlines, live session attendance (where mandatory), and project milestone submissions. These are non-negotiable components of the programme." },
    { id: "11.9", category: "11. Spurti Points", question: "11.9 What does 'rolling basis' mean?", answer: "'Rolling basis' means your participation is evaluated over a moving window of time (e.g., the last 7 days) rather than cumulatively from day 1. This means recent consistent participation can improve your standing even if you had a slow start." },
    { id: "11.10", category: "11. Spurti Points", question: "11.10 What happens if I fall below the required participation level?", answer: "You'll receive a notification/warning on your dashboard. You'll have a grace period to bring your participation back up. If participation remains below the threshold after the warning period, further action may be taken including potential removal from the programme." },
    { id: "11.11", category: "11. Spurti Points", question: "11.11 How are Spurti Points calculated?", answer: "SP is calculated from multiple weighted factors: live session attendance, coursework completion rate, Rosetta journal consistency, standup participation, and project contributions. The exact weights may vary by phase and are detailed on your dashboard." },
    { id: "11.12", category: "11. Spurti Points", question: "11.12 Can the programme team award or deduct SP directly?", answer: "Yes, the programme team can make manual adjustments to SP in exceptional cases — for example, awarding bonus SP for outstanding contributions or deducting SP for code of conduct violations. Such adjustments are documented and communicated." },

    // --- Section 12: Yaksha Chat Related ---
    { id: "12.1", category: "12. Yaksha Chat Related", question: "12.1 I'm unable to type in the chat after clicking 'Interact with Yaksha' — what should I do?", answer: "Try refreshing the page and clicking the button again. If the issue persists, try a different browser or clear your cache. This is usually a temporary browser issue. If it continues, report it through email to the support team." },

    // --- Section 13: ViBe Platform ---
    { id: "13.1", category: "13. ViBe Platform", question: "13.1 How do I log in to ViBe?", answer: "Use the invite link provided on your Samagama dashboard. Log in with the email you registered with (preferably your Samagama email). If you face login issues, check that you're using the correct email and try resetting your password." },
    { id: "13.2", category: "13. ViBe Platform", question: "13.2 Invite accepted but shows 'No course enrolled'?", answer: "This usually means the course hasn't been assigned to your account yet. Wait 24 hours and try again. If the issue persists, contact the programme team with your ViBe email address so they can manually enroll you." },
    { id: "13.3", category: "13. ViBe Platform", question: "13.3 Why are videos stuck or repeating?", answer: "Video playback issues are usually caused by: slow internet, browser cache issues, or ad blockers. Try: (1) clearing cache, (2) disabling extensions, (3) using Chrome, (4) checking your internet speed. If the problem persists, report it with your browser details." },
    { id: "13.4", category: "13. ViBe Platform", question: "13.4 Can I use a mobile or tablet?", answer: "ViBe is optimized for desktop/laptop browsers. While it may work on mobile/tablet, the experience may be suboptimal, especially for quizzes and interactive content. We recommend using a laptop or desktop for the best experience." },
    { id: "13.5", category: "13. ViBe Platform", question: "13.5 I'm experiencing video issues (stuck, looping, skipping) on ViBe. How do I troubleshoot?", answer: "Try these steps in order: (1) Refresh the page, (2) Clear browser cache and cookies, (3) Disable all extensions/ad blockers, (4) Try a different browser (Chrome recommended), (5) Check your internet connection, (6) Try in incognito/private mode. If none work, report the issue." },
    { id: "13.6", category: "13. ViBe Platform", question: "13.6 I have completed all videos and quizzes in the ViBe course, but my progress is still showing less than 100%. What should I do?", answer: "Progress tracking may have a delay. Wait 24 hours and check again. If it still doesn't update, ensure you've completed ALL items including any hidden/optional sections. Report the issue with screenshots of your completion status." },
    { id: "13.7", category: "13. ViBe Platform", question: "13.7 I feel the ViBe content or platform is not good or I am unhappy with the way progress is evaluated. Can I request an exception or bypass the system?", answer: "We appreciate feedback about the platform and content. However, the coursework requirements are standard for all interns and exceptions are not granted. If you have constructive feedback, share it through the dashboard — it helps us improve for future cohorts." },
    { id: "13.8", category: "13. ViBe Platform", question: "13.8 Is the ViBe consent form compulsory? What if I don't want to grant camera access?", answer: "The consent form and camera access are part of the proctoring system to ensure academic integrity. They are mandatory for completing assessed content. If you have privacy concerns, contact the programme team to discuss alternatives, though options may be limited." },
    { id: "13.9", category: "13. ViBe Platform", question: "13.9 What are penalty scores on the ViBe platform, and how do they affect our performance or HP?", answer: "Penalty scores are deducted for violations detected during proctored sessions (e.g., looking away from screen, multiple faces detected, tab switching). They affect your course completion score. Minimize penalties by following the proctoring guidelines carefully." },
    { id: "13.10", category: "13. ViBe Platform", question: "13.10 When should I use the Flag option on ViBe, and when should I contact support?", answer: "Use the Flag option for content issues (incorrect questions, unclear instructions, broken media). Contact support for technical issues (login problems, progress not updating, platform errors). Flagging helps the content team improve materials." },
    { id: "13.11", category: "13. ViBe Platform", question: "13.11 What is Linear Progression on ViBe?", answer: "Linear Progression means you must complete modules in order — you cannot skip ahead to later sections without completing earlier ones. This ensures you build knowledge sequentially and don't miss foundational concepts." },
    { id: "13.12", category: "13. ViBe Platform", question: "13.12 Can I use the left navigation panel to jump ahead to a later video or quiz?", answer: "No, due to Linear Progression, you cannot jump ahead. You must complete each item in sequence. The navigation panel shows your progress but locked items cannot be accessed until prerequisites are completed." },
    { id: "13.13", category: "13. ViBe Platform", question: "13.13 I am seeing a red 'Access Restricted' banner. Is this a bug?", answer: "The 'Access Restricted' banner usually appears when you try to access content that's locked due to Linear Progression or when your enrollment hasn't been fully processed. Complete the preceding items first. If you believe it's an error, contact support." },
    { id: "13.14", category: "13. ViBe Platform", question: "13.14 How do I resolve the 'Access Restricted' error?", answer: "First, ensure you've completed all previous modules in sequence. If you have and still see the error: (1) refresh the page, (2) log out and log back in, (3) clear cache. If it persists, report it to support with a screenshot." },
    { id: "13.15", category: "13. ViBe Platform", question: "13.15 Why does ViBe sometimes make me re-watch a clip after a quiz?", answer: "This is by design. If you scored below a certain threshold on a quiz, the system may require you to re-watch the relevant content before retaking the quiz. This ensures you've properly understood the material before proceeding." },
    { id: "13.16", category: "13. ViBe Platform", question: "13.16 What kinds of quiz questions will I see on ViBe?", answer: "Quiz questions include multiple choice, true/false, short answer, and code-based questions. They test your understanding of the video content you just watched. Read each question carefully and refer back to the material if needed." },
    { id: "13.17", category: "13. ViBe Platform", question: "13.17 Are the same proctoring rules applied to every course on ViBe?", answer: "Proctoring rules may vary by course and assessment type. Some quizzes may be proctored while others are not. The proctoring status is indicated before you start each assessment. Follow the guidelines shown for each specific assessment." },
    { id: "13.18", category: "13. ViBe Platform", question: "13.18 What does the 'quiet helper' on ViBe actually do?", answer: "The 'quiet helper' is an AI-assisted feature that can answer basic questions about the course content. It's designed to help you when you're stuck on a concept without having to wait for human support. Use it for quick clarifications." },
    { id: "13.19", category: "13. ViBe Platform", question: "13.19 Does ViBe record long videos of me while I'm learning?", answer: "ViBe uses camera access for proctoring during assessments only, not during regular video watching. The proctoring captures snapshots at intervals during quizzes to verify identity and ensure academic integrity. Continuous video recording does not happen during learning." },
    { id: "13.20", category: "13. ViBe Platform", question: "13.20 What is the single most common avoidable mistake learners make?", answer: "The most common mistake is rushing through videos without truly understanding the content, then struggling with quizzes. Take your time, take notes, and ensure you understand each concept before moving on. Quality of learning matters more than speed." },
    { id: "13.21", category: "13. ViBe Platform", question: "13.21 Why does the lesson keep pausing or restarting even when I'm paying attention?", answer: "This may be due to the attention detection system. Ensure: (1) your face is clearly visible to the camera, (2) you're looking at the screen, (3) lighting is adequate, (4) no other faces are in frame. If the issue persists despite these, report it as a technical issue." },
    { id: "13.22", category: "13. ViBe Platform", question: "13.22 Can I read the quiz questions aloud or mutter to myself while watching?", answer: "Yes, reading aloud or muttering to yourself is fine and won't trigger any proctoring violations. The system monitors visual cues, not audio. However, avoid having conversations with others during proctored assessments." },
    { id: "13.23", category: "13. ViBe Platform", question: "13.23 Can I study with a friend on camera since we're learning together?", answer: "During regular video watching, having others nearby is fine. However, during proctored assessments, only YOU should be visible on camera. Multiple faces detected during a proctored quiz will trigger a violation. Study together, but take assessments individually." },
    { id: "13.24", category: "13. ViBe Platform", question: "13.24 Will I lose my progress if I clear my browser or reinstall it?", answer: "No, your progress is saved on the server, not locally. Clearing your browser or reinstalling won't affect your course progress. Simply log back in with your credentials and your progress will be intact." },
    { id: "13.25", category: "13. ViBe Platform", question: "13.25 Is there a recommended daily learning rhythm on ViBe?", answer: "We recommend 1–2 hours of focused ViBe learning per day. Consistency is key — it's better to do 1 hour daily than 7 hours once a week. Set a regular time slot for your coursework and stick to it." },
    { id: "13.26", category: "13. ViBe Platform", question: "13.26 What should my 'study corner' look like before I start a ViBe session?", answer: "Ensure: (1) good lighting on your face, (2) clean background, (3) no other people visible, (4) stable internet, (5) quiet environment, (6) camera at eye level, (7) no distracting items. This setup helps with both proctoring and your own focus." },
    { id: "13.27", category: "13. ViBe Platform", question: "13.27 I'm facing a technical issue on ViBe that I can't resolve. Is there live support available?", answer: "For urgent ViBe technical issues, use the Samagama dashboard chat during business hours. For non-urgent issues, email the support team with details (screenshots, browser info, error messages). Response time is typically within 24 hours." },

    // --- Section 14: Team Formation ---
    { id: "14.1", category: "14. Team Formation", question: "14.1 Is team formation compulsory?", answer: "Yes, team formation is a required part of the internship. You will be assigned to or form a team for the project phase. Working in teams is essential for developing collaboration skills and tackling larger projects." },
    { id: "14.2", category: "14. Team Formation", question: "14.2 What is the size of a team?", answer: "Team sizes typically range from 3–5 members, depending on the project and cohort size. The exact team size for your cohort will be announced during the team formation activity." },
    { id: "14.3", category: "14. Team Formation", question: "14.3 How are teams formed?", answer: "Teams are formed through a structured activity where you can express preferences and connect with other interns. The final team assignments consider skill diversity, timezone compatibility, and project interests. The programme team facilitates the process." },
    { id: "14.4", category: "14. Team Formation", question: "14.4 I started on May 15/16 but couldn't form a team during the activity. What happens now?", answer: "If you missed the team formation activity, the programme team will assign you to a team. You won't be left without a team. Check your dashboard for your team assignment or contact the programme team for an update." },
    { id: "14.5", category: "14. Team Formation", question: "14.5 There was a typo in our email addresses during team formation. Can we fix it?", answer: "Yes, contact the programme team immediately through the dashboard chat with the correct email addresses. They can update the records. Do this as soon as possible to avoid communication issues with your team." },
    { id: "14.6", category: "14. Team Formation", question: "14.6 I formed a team with only two members. Will it be considered?", answer: "Teams below the minimum size may be merged with other small teams or have additional members assigned by the programme team. You won't be penalized, but your final team composition may differ from your initial formation." },
    { id: "14.7", category: "14. Team Formation", question: "14.7 What if a team member leaves or becomes ineligible during Phase 1?", answer: "If a team member drops out, the programme team will either assign a replacement or redistribute the workload. Your team won't be disadvantaged due to a member leaving. Inform the programme team as soon as you become aware of the situation." },
    { id: "14.8", category: "14. Team Formation", question: "14.8 Can I form a team with someone from my own college?", answer: "Yes, you can form a team with college-mates. However, we encourage diverse teams with members from different institutions as it provides broader perspectives and networking opportunities." },
    { id: "14.9", category: "14. Team Formation", question: "14.9 Can I form a team with students from my IIT MBS cohort?", answer: "Yes, you can form teams with students from the same cohort. The team formation activity allows you to connect with and choose teammates from within your cohort." },
    { id: "14.10", category: "14. Team Formation", question: "14.10 Can we change our team name after submission?", answer: "Team name changes after submission are generally not supported as they affect record-keeping. Choose your team name carefully during formation. If there's a compelling reason (e.g., inappropriate name was submitted by mistake), contact the programme team." },
    { id: "14.11", category: "14. Team Formation", question: "14.11 What if multiple teams choose the same name?", answer: "If duplicate team names occur, the programme team may ask one or more teams to choose a different name. Priority is typically given to the team that submitted first." },
    { id: "14.12", category: "14. Team Formation", question: "14.12 What should I do if I face issues within my team?", answer: "First, try to resolve issues through open communication with your teammates. If that doesn't work, escalate to your mentor. If the issue persists, contact the programme team through the dashboard. Document specific instances to help the team understand the situation." },
    { id: "14.13", category: "14. Team Formation", question: "14.13 How will I know who my mentor is?", answer: "Your mentor assignment will be communicated via your dashboard and email after team formation is complete. You'll see your mentor's name and contact information on your team page." },
    { id: "14.14", category: "14. Team Formation", question: "14.14 When will I know my team details?", answer: "Team details are finalized and shared within a few days after the team formation activity. Check your dashboard regularly for updates. You'll also receive an email notification when your team is confirmed." },
    { id: "14.15", category: "14. Team Formation", question: "14.15 I received a team list email but my name is not included. What should I do?", answer: "Contact the programme team immediately through the dashboard chat. This may be an administrative error. Provide your full name, Samagama email, and the team you expected to be in. The team will verify and correct the records." },
    { id: "14.16", category: "14. Team Formation", question: "14.16 We selected Project X as our top priority but were assigned Project Y. Can we change it?", answer: "Project assignments consider multiple factors including team skills, project capacity, and overall distribution. Changes are generally not possible once assigned. Trust the process — you may find Project Y equally or more rewarding than your initial preference." },
    { id: "14.17", category: "14. Team Formation", question: "14.17 I just started the internship. Can I form my own team now?", answer: "Team formation happens at a specific time during the internship. If you've just started, wait for the team formation activity to be announced. You cannot form teams independently outside the official process." },
    { id: "14.18", category: "14. Team Formation", question: "14.18 When do team activities begin?", answer: "Team activities typically begin in Phase 2, after the individual coursework phase is complete. The exact timeline is communicated on your dashboard and during live sessions. Focus on Phase 1 coursework until team activities are announced." },
    { id: "14.19", category: "14. Team Formation", question: "14.19 Can I request a specific teammate after teams are assigned?", answer: "Once teams are finalized, member changes are not accommodated based on personal preferences. The team formation process is designed to be fair and balanced. Work with your assigned team and make the best of the collaboration." },
    { id: "14.20", category: "14. Team Formation", question: "14.20 What happens if a team member is inactive or not contributing?", answer: "First, try reaching out to the inactive member directly. If there's no response, inform your mentor. The programme team tracks individual contributions and may take action (warnings, SP deductions, or removal) for consistently inactive members." },
    { id: "14.21", category: "14. Team Formation", question: "14.21 Can I switch teams if there are conflicts?", answer: "Team switches are handled on a case-by-case basis and only for serious conflicts that cannot be resolved through mediation. Contact the programme team with specific details. Switching is not guaranteed and is a last resort." },
    { id: "14.22", category: "14. Team Formation", question: "14.22 Will team performance affect individual evaluation?", answer: "Evaluation has both team and individual components. While the team's overall output matters, individual contributions are tracked separately. You won't be penalized for a teammate's lack of effort if your own contributions are documented and consistent." },
    { id: "14.23", category: "14. Team Formation", question: "14.23 How will communication happen within teams?", answer: "Teams can use any communication tool they agree on (Discord, Slack, WhatsApp, etc.) for internal coordination. However, official submissions and milestone updates must go through the Samagama platform. Establish clear communication norms early with your team." },
    { id: "14.24", category: "14. Team Formation", question: "14.24 What if I miss the team allocation announcement?", answer: "Check your dashboard and email (including spam folder). Team allocation information is always available on your dashboard. If you still can't find it, contact the programme team. Missing the announcement doesn't affect your team assignment." },
    { id: "14.25", category: "14. Team Formation", question: "14.25 Can a team be dissolved and reformed?", answer: "Team dissolution is extremely rare and only happens in exceptional circumstances (e.g., majority of members dropping out). The programme team makes this decision. If you're facing team issues, reach out for mediation before requesting dissolution." },
    { id: "14.26", category: "14. Team Formation", question: "14.26 What happens if I drop out of the internship?", answer: "If you need to drop out, inform the programme team as soon as possible through the dashboard. Your team will be notified and adjustments will be made. Note that dropping out means you won't receive a completion certificate for that cycle." },
    { id: "14.27", category: "14. Team Formation", question: "14.27 Will we get time to get to know our teammates before Phase 2?", answer: "Yes, there is typically a brief 'team bonding' period after team formation where you can introduce yourselves, discuss working styles, and set expectations. Use this time wisely — strong team dynamics early on lead to better project outcomes." }
];

async function seedDatabase() {
    console.log("🛠️ Checking and creating tables if they don't exist...");
    
    try {
        // 1. Automatically create 'faqs' table (Purane FAQs ke liye)
        await db.execute(`
            CREATE TABLE IF NOT EXISTS faqs (
                id TEXT PRIMARY KEY,
                category TEXT,
                question TEXT,
                answer TEXT
            )
        `);
        console.log("✅ 'faqs' table is ready!");

        // 2. Automatically create 'community_faqs' table (Naye FAQs ke liye)
        await db.execute(`
            CREATE TABLE IF NOT EXISTS community_faqs (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                category TEXT NOT NULL,
                question TEXT NOT NULL,
                answer TEXT,
                views INTEGER DEFAULT 0,
                status TEXT DEFAULT 'approved',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        `);
        console.log("✅ 'community_faqs' table is ready!\n");

        // 3. Automatically create 'users' table (Auth system ke liye)
        await db.execute(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                fullname TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        `);
        console.log("✅ 'users' table is ready!\n");

        console.log("🌱 Database me data feed karna shuru kar rahe hain...");
        let count = 0;
        
        for (const faq of oldFaqs) {
            // Check karein ki FAQ pehle se toh nahi hai
            const check = await db.execute({
                sql: "SELECT id FROM faqs WHERE id = ?",
                args: [faq.id]
            });

            // Agar nahi hai, toh insert karein
            if (check.rows.length === 0) {
                await db.execute({
                    sql: "INSERT INTO faqs (id, category, question, answer) VALUES (?, ?, ?, ?)",
                    args: [faq.id, faq.category, faq.question, faq.answer]
                });
                console.log(`✅ Inserted: ${faq.id}`);
                count++;
            } else {
                console.log(`⏭️ Skipped (Already exists): ${faq.id}`);
            }
        }
        
        console.log(`\n🎉 Seed complete! Total ${count} FAQs add kiye gaye.`);
        console.log("Ab aapka database puri tarah set hai!");
    } catch (error) {
        console.error("❌ Seeding me error aayi:", error.message);
    }
}

seedDatabase();